
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;



/*
 * Copyright (C) 2018 Matan Davidi
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * @author Matan Davidi
 */
public class ChangeColorFrame extends JFrame {

    Game parentGame;

    /**
     * Creates new form ChangeColorFrame
     *
     * @param parentGame
     */
    public ChangeColorFrame(Game parentGame) {
        initComponents();
        this.parentGame = parentGame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        colorLabel = new JLabel();
        redButton = new JButton();
        yellowButton = new JButton();
        greenButton = new JButton();
        blueButton = new JButton();

        setDefaultCloseOperation(HIDE_ON_CLOSE);

        colorLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        colorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        colorLabel.setText("Please pick a color");
        getContentPane().add(colorLabel, java.awt.BorderLayout.CENTER);

        redButton.setText("RED");
        redButton.addMouseListener(parentGame);
        getContentPane().add(redButton, java.awt.BorderLayout.PAGE_START);

        yellowButton.setText("YELLOW");
        yellowButton.addMouseListener(parentGame);
        getContentPane().add(yellowButton, java.awt.BorderLayout.LINE_END);

        greenButton.setText("GREEN");
        greenButton.addMouseListener(parentGame);
        getContentPane().add(greenButton, java.awt.BorderLayout.LINE_START);

        blueButton.setText("BLUE");
        blueButton.addMouseListener(parentGame);
        getContentPane().add(blueButton, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>                        

    // Variables declaration - do not modify                     
    private javax.swing.JButton blueButton;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JButton greenButton;
    private javax.swing.JButton redButton;
    private javax.swing.JButton yellowButton;
    // End of variables declaration                   
}
